add_newline = true


[directory]
truncation_length = 8
truncation_symbol = "…/"


[username]
disabled = false
show_always = true
format = "[$user]($style)[@](bold)"


[hostname]
disabled = false
ssh_only = false

