add_newline = true
format = """
$username\
$hostname\
$kubernetes\
$directory\
$vcsh\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$docker_context\
$package\
$cmake\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$golang\
$helm\
$java\
$julia\
$kotlin\
$nim\
$nodejs\
$ocaml\
$perl\
$php\
$purescript\
$python\
$red\
$ruby\
$rust\
$scala\
$swift\
$terraform\
$vlang\
$vagrant\
$zig\
$nix_shell\
$conda\
$memory_usage\
$aws\
$gcloud\
$openstack\
$env_var\
$crystal\
$custom\
$cmd_duration\
$line_break\
$lua\
$jobs\
$battery\
$time\
$status\
$shlvl\
$shell\
$character"""


[shell]
disabled = false
fish_indicator = "fish"
bash_indicator = "bash"
format = "[$indicator](bold #EB7434) "

[shlvl]
disabled = false
format = "[$shlvl](bold):"


[directory]
truncation_length = 8
truncation_symbol = "…/"


[username]
disabled = false
show_always = true
format = "[$user]($style)[@](bold)"


[hostname]
disabled = false
ssh_only = false

